"""meal items for food diary

Revision ID: 3285fe4e97cf
Revises: 47eb20abf95f
Create Date: 2026-09-10 19:27:36.216102
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3285fe4e97cf'
down_revision: Union[str, None] = '47eb20abf95f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meal_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meal_log_id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('quantity_g', sa.Float(), nullable=False),
    sa.Column('kcal', sa.Float(), nullable=False),
    sa.Column('protein_g', sa.Float(), nullable=False),
    sa.Column('carbs_g', sa.Float(), nullable=False),
    sa.Column('fat_g', sa.Float(), nullable=False),
    sa.Column('fiber_g', sa.Float(), nullable=True),
    sa.Column('sugars_g', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['meal_log_id'], ['meal_logs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meal_items_meal_log_id'), 'meal_items', ['meal_log_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_meal_items_meal_log_id'), table_name='meal_items')
    op.drop_table('meal_items')
    # ### end Alembic commands ###
