"""training feedback and exercise preferences

Revision ID: 47eb20abf95f
Revises: ee42a2939aca
Create Date: 2026-09-10 15:22:41.033759
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47eb20abf95f'
down_revision: Union[str, None] = 'ee42a2939aca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercise_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('is_preferred', sa.Boolean(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_id'], ['user_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercise_preferences_exercise_id'), 'exercise_preferences', ['exercise_id'], unique=False)
    op.create_index(op.f('ix_exercise_preferences_is_preferred'), 'exercise_preferences', ['is_preferred'], unique=False)
    op.create_index(op.f('ix_exercise_preferences_profile_id'), 'exercise_preferences', ['profile_id'], unique=False)
    op.create_index('ix_preference_profile_exercise', 'exercise_preferences', ['profile_id', 'exercise_id'], unique=True)
    op.create_table('training_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('workout_plan_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('progress_perception', sa.String(length=16), nullable=False),
    sa.Column('recovery_quality', sa.String(length=16), nullable=False),
    sa.Column('doms_duration_hours', sa.Integer(), nullable=True),
    sa.Column('affects_performance', sa.Boolean(), nullable=False),
    sa.Column('sleep_quality', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['user_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workout_plan_id'], ['workout_plans.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_feedback_date'), 'training_feedback', ['date'], unique=False)
    op.create_index(op.f('ix_training_feedback_profile_id'), 'training_feedback', ['profile_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_training_feedback_profile_id'), table_name='training_feedback')
    op.drop_index(op.f('ix_training_feedback_date'), table_name='training_feedback')
    op.drop_table('training_feedback')
    op.drop_index('ix_preference_profile_exercise', table_name='exercise_preferences')
    op.drop_index(op.f('ix_exercise_preferences_profile_id'), table_name='exercise_preferences')
    op.drop_index(op.f('ix_exercise_preferences_is_preferred'), table_name='exercise_preferences')
    op.drop_index(op.f('ix_exercise_preferences_exercise_id'), table_name='exercise_preferences')
    op.drop_table('exercise_preferences')
    # ### end Alembic commands ###
