"""initial fitness and nutrition schema

Revision ID: ee42a2939aca
Revises: 
Create Date: 2026-09-10 13:42:27.289624
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee42a2939aca'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wger_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('primary_muscle', sa.String(length=120), nullable=True),
    sa.Column('secondary_muscles', sa.Text(), nullable=True),
    sa.Column('equipment', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=120), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('is_compound', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('wger_id')
    )
    op.create_index(op.f('ix_exercises_name'), 'exercises', ['name'], unique=False)
    op.create_index(op.f('ix_exercises_primary_muscle'), 'exercises', ['primary_muscle'], unique=False)
    op.create_table('ingredients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('source_id', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('kcal_100g', sa.Float(), nullable=False),
    sa.Column('protein_100g', sa.Float(), nullable=False),
    sa.Column('carbs_100g', sa.Float(), nullable=False),
    sa.Column('fat_100g', sa.Float(), nullable=False),
    sa.Column('sugars_100g', sa.Float(), nullable=True),
    sa.Column('fiber_100g', sa.Float(), nullable=True),
    sa.Column('saturated_fat_100g', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ingredient_source_id', 'ingredients', ['source', 'source_id'], unique=False)
    op.create_index(op.f('ix_ingredients_name'), 'ingredients', ['name'], unique=False)
    op.create_index(op.f('ix_ingredients_source'), 'ingredients', ['source'], unique=False)
    op.create_index(op.f('ix_ingredients_source_id'), 'ingredients', ['source_id'], unique=False)
    op.create_table('recipes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('source_id', sa.String(length=64), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('servings', sa.Integer(), nullable=False),
    sa.Column('is_vegetarian', sa.Boolean(), nullable=False),
    sa.Column('is_vegan', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recipes_is_vegan'), 'recipes', ['is_vegan'], unique=False)
    op.create_index(op.f('ix_recipes_is_vegetarian'), 'recipes', ['is_vegetarian'], unique=False)
    op.create_index(op.f('ix_recipes_name'), 'recipes', ['name'], unique=False)
    op.create_table('user_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('sex', sa.String(length=16), nullable=False),
    sa.Column('height_cm', sa.Float(), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=False),
    sa.Column('goal', sa.String(length=32), nullable=False),
    sa.Column('experience_level', sa.String(length=32), nullable=False),
    sa.Column('activity_level', sa.String(length=32), nullable=False),
    sa.Column('diet_type', sa.String(length=32), nullable=False),
    sa.Column('available_equipment', sa.Text(), nullable=True),
    sa.Column('food_exclusions', sa.Text(), nullable=True),
    sa.Column('training_days_per_week', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_recommendation_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('recommendation_type', sa.String(length=48), nullable=False),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('knowledge_source_tags', sa.String(length=500), nullable=True),
    sa.Column('used_llm', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['user_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_recommendation_log_created_at'), 'agent_recommendation_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_agent_recommendation_log_profile_id'), 'agent_recommendation_log', ['profile_id'], unique=False)
    op.create_index(op.f('ix_agent_recommendation_log_recommendation_type'), 'agent_recommendation_log', ['recommendation_type'], unique=False)
    op.create_table('meal_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('meal_type', sa.String(length=32), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('servings', sa.Float(), nullable=False),
    sa.Column('kcal', sa.Float(), nullable=True),
    sa.Column('protein_g', sa.Float(), nullable=True),
    sa.Column('carbs_g', sa.Float(), nullable=True),
    sa.Column('fat_g', sa.Float(), nullable=True),
    sa.Column('is_planned', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['user_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meal_logs_date'), 'meal_logs', ['date'], unique=False)
    op.create_index(op.f('ix_meal_logs_profile_id'), 'meal_logs', ['profile_id'], unique=False)
    op.create_index('ix_meal_profile_date', 'meal_logs', ['profile_id', 'date'], unique=False)
    op.create_table('nutrition_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('goal', sa.String(length=32), nullable=False),
    sa.Column('target_kcal', sa.Float(), nullable=False),
    sa.Column('target_protein_g', sa.Float(), nullable=False),
    sa.Column('target_carbs_g', sa.Float(), nullable=False),
    sa.Column('target_fat_g', sa.Float(), nullable=False),
    sa.Column('target_fiber_g', sa.Float(), nullable=False),
    sa.Column('calorie_adjustment_pct', sa.Float(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('started_at', sa.Date(), nullable=False),
    sa.Column('ended_at', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['user_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nutrition_plans_is_active'), 'nutrition_plans', ['is_active'], unique=False)
    op.create_index(op.f('ix_nutrition_plans_profile_id'), 'nutrition_plans', ['profile_id'], unique=False)
    op.create_table('recipe_ingredients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('quantity_g', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recipe_ingredients_ingredient_id'), 'recipe_ingredients', ['ingredient_id'], unique=False)
    op.create_index(op.f('ix_recipe_ingredients_recipe_id'), 'recipe_ingredients', ['recipe_id'], unique=False)
    op.create_table('screening_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('heart_condition', sa.Boolean(), nullable=False),
    sa.Column('chest_pain', sa.Boolean(), nullable=False),
    sa.Column('dizziness_loss_consciousness', sa.Boolean(), nullable=False),
    sa.Column('chronic_condition', sa.Boolean(), nullable=False),
    sa.Column('blood_pressure_heart_medication', sa.Boolean(), nullable=False),
    sa.Column('bone_joint_problem', sa.Boolean(), nullable=False),
    sa.Column('pregnant_or_postpartum', sa.Boolean(), nullable=False),
    sa.Column('eating_disorder_history', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['user_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_screening_records_profile_id'), 'screening_records', ['profile_id'], unique=False)
    op.create_table('supplement_declarations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=True),
    sa.Column('dose_amount', sa.Float(), nullable=True),
    sa.Column('dose_unit', sa.String(length=16), nullable=True),
    sa.Column('doses_per_day', sa.Float(), nullable=False),
    sa.Column('timing', sa.String(length=120), nullable=True),
    sa.Column('protein_g_per_dose', sa.Float(), nullable=True),
    sa.Column('agent_assessment', sa.Text(), nullable=True),
    sa.Column('knowledge_source_tag', sa.String(length=64), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['user_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supplement_declarations_is_active'), 'supplement_declarations', ['is_active'], unique=False)
    op.create_index(op.f('ix_supplement_declarations_kind'), 'supplement_declarations', ['kind'], unique=False)
    op.create_index(op.f('ix_supplement_declarations_profile_id'), 'supplement_declarations', ['profile_id'], unique=False)
    op.create_table('weight_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=False),
    sa.Column('body_fat_pct', sa.Float(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['user_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weight_logs_date'), 'weight_logs', ['date'], unique=False)
    op.create_index(op.f('ix_weight_logs_profile_id'), 'weight_logs', ['profile_id'], unique=False)
    op.create_index('ix_weight_profile_date', 'weight_logs', ['profile_id', 'date'], unique=False)
    op.create_table('workout_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('goal', sa.String(length=32), nullable=False),
    sa.Column('days_per_week', sa.Integer(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('started_at', sa.Date(), nullable=False),
    sa.Column('ended_at', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['user_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workout_plans_is_active'), 'workout_plans', ['is_active'], unique=False)
    op.create_index(op.f('ix_workout_plans_profile_id'), 'workout_plans', ['profile_id'], unique=False)
    op.create_table('workout_plan_exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workout_plan_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('day_label', sa.String(length=32), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('target_sets', sa.Integer(), nullable=False),
    sa.Column('target_reps_min', sa.Integer(), nullable=False),
    sa.Column('target_reps_max', sa.Integer(), nullable=False),
    sa.Column('target_rir', sa.Integer(), nullable=False),
    sa.Column('rest_seconds', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workout_plan_id'], ['workout_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workout_plan_exercises_exercise_id'), 'workout_plan_exercises', ['exercise_id'], unique=False)
    op.create_index(op.f('ix_workout_plan_exercises_workout_plan_id'), 'workout_plan_exercises', ['workout_plan_id'], unique=False)
    op.create_table('workout_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('workout_plan_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('day_label', sa.String(length=32), nullable=True),
    sa.Column('perceived_fatigue', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['user_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workout_plan_id'], ['workout_plans.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workout_sessions_date'), 'workout_sessions', ['date'], unique=False)
    op.create_index(op.f('ix_workout_sessions_profile_id'), 'workout_sessions', ['profile_id'], unique=False)
    op.create_index(op.f('ix_workout_sessions_workout_plan_id'), 'workout_sessions', ['workout_plan_id'], unique=False)
    op.create_table('session_sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workout_session_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('set_number', sa.Integer(), nullable=False),
    sa.Column('reps', sa.Integer(), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=False),
    sa.Column('rir', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workout_session_id'], ['workout_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_sets_exercise_id'), 'session_sets', ['exercise_id'], unique=False)
    op.create_index(op.f('ix_session_sets_workout_session_id'), 'session_sets', ['workout_session_id'], unique=False)
    op.create_index('ix_set_exercise_session', 'session_sets', ['exercise_id', 'workout_session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_set_exercise_session', table_name='session_sets')
    op.drop_index(op.f('ix_session_sets_workout_session_id'), table_name='session_sets')
    op.drop_index(op.f('ix_session_sets_exercise_id'), table_name='session_sets')
    op.drop_table('session_sets')
    op.drop_index(op.f('ix_workout_sessions_workout_plan_id'), table_name='workout_sessions')
    op.drop_index(op.f('ix_workout_sessions_profile_id'), table_name='workout_sessions')
    op.drop_index(op.f('ix_workout_sessions_date'), table_name='workout_sessions')
    op.drop_table('workout_sessions')
    op.drop_index(op.f('ix_workout_plan_exercises_workout_plan_id'), table_name='workout_plan_exercises')
    op.drop_index(op.f('ix_workout_plan_exercises_exercise_id'), table_name='workout_plan_exercises')
    op.drop_table('workout_plan_exercises')
    op.drop_index(op.f('ix_workout_plans_profile_id'), table_name='workout_plans')
    op.drop_index(op.f('ix_workout_plans_is_active'), table_name='workout_plans')
    op.drop_table('workout_plans')
    op.drop_index('ix_weight_profile_date', table_name='weight_logs')
    op.drop_index(op.f('ix_weight_logs_profile_id'), table_name='weight_logs')
    op.drop_index(op.f('ix_weight_logs_date'), table_name='weight_logs')
    op.drop_table('weight_logs')
    op.drop_index(op.f('ix_supplement_declarations_profile_id'), table_name='supplement_declarations')
    op.drop_index(op.f('ix_supplement_declarations_kind'), table_name='supplement_declarations')
    op.drop_index(op.f('ix_supplement_declarations_is_active'), table_name='supplement_declarations')
    op.drop_table('supplement_declarations')
    op.drop_index(op.f('ix_screening_records_profile_id'), table_name='screening_records')
    op.drop_table('screening_records')
    op.drop_index(op.f('ix_recipe_ingredients_recipe_id'), table_name='recipe_ingredients')
    op.drop_index(op.f('ix_recipe_ingredients_ingredient_id'), table_name='recipe_ingredients')
    op.drop_table('recipe_ingredients')
    op.drop_index(op.f('ix_nutrition_plans_profile_id'), table_name='nutrition_plans')
    op.drop_index(op.f('ix_nutrition_plans_is_active'), table_name='nutrition_plans')
    op.drop_table('nutrition_plans')
    op.drop_index('ix_meal_profile_date', table_name='meal_logs')
    op.drop_index(op.f('ix_meal_logs_profile_id'), table_name='meal_logs')
    op.drop_index(op.f('ix_meal_logs_date'), table_name='meal_logs')
    op.drop_table('meal_logs')
    op.drop_index(op.f('ix_agent_recommendation_log_recommendation_type'), table_name='agent_recommendation_log')
    op.drop_index(op.f('ix_agent_recommendation_log_profile_id'), table_name='agent_recommendation_log')
    op.drop_index(op.f('ix_agent_recommendation_log_created_at'), table_name='agent_recommendation_log')
    op.drop_table('agent_recommendation_log')
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_recipes_name'), table_name='recipes')
    op.drop_index(op.f('ix_recipes_is_vegetarian'), table_name='recipes')
    op.drop_index(op.f('ix_recipes_is_vegan'), table_name='recipes')
    op.drop_table('recipes')
    op.drop_index(op.f('ix_ingredients_source_id'), table_name='ingredients')
    op.drop_index(op.f('ix_ingredients_source'), table_name='ingredients')
    op.drop_index(op.f('ix_ingredients_name'), table_name='ingredients')
    op.drop_index('ix_ingredient_source_id', table_name='ingredients')
    op.drop_table('ingredients')
    op.drop_index(op.f('ix_exercises_primary_muscle'), table_name='exercises')
    op.drop_index(op.f('ix_exercises_name'), table_name='exercises')
    op.drop_table('exercises')
    # ### end Alembic commands ###
