"""split type preference

Revision ID: fd5373cb67e4
Revises: 7633e6279bb7
Create Date: 2026-09-10 21:19:50.807452
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd5373cb67e4'
down_revision: Union[str, None] = '7633e6279bb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default: le righe già esistenti devono ricevere un valore. Il
    # default Python vale solo per i nuovi oggetti creati dall'applicazione,
    # non per chi è già nel database.
    op.add_column(
        'user_profiles',
        sa.Column('split_type', sa.String(length=32), nullable=False, server_default='auto'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'split_type')
    # ### end Alembic commands ###
